### PR TITLE
Added Injection.inject(Object object) to make the injection flow more consistent across all classes

### PR DESCRIPTION
**Pull request by charly1811**
Injection.inject() just like in Dagger initializes injectable fields. This method is equivalent to DaggerComponent.inject()

### CODE REVIEW

**Comment by chiuki** [comment]
Can you make the whitespace match the existing code? Thanks!

**Comment by chiuki** [comment]
Sorry didn't mention it in the last comment: Please squash so I can see the changes without being distracted by the whitespaces. http://stackoverflow.com/a/5201642/295797

**Comment by charly1811** [comment]
Of course ! Sorry about that .

**Comment by chiuki** [comment]
I am very very sorry, I don't think I'll take this PR after all.

This repo goes with my book:
https://gum.co/DaggerlessDITesting

I don't think I have time to rewrite the book to explain this new structure to the app. I'm very sorry. Should have looked into the code even with all the whitespace changes.

**Comment by charly1811** [comment]
No problem ! Interesting book BTW :)

**Pull request closed without merging**
